[tool.poetry]
name = "s3-sandbox"
version = "0.1.0"
description = "A project to try AWS S3."
authors = ["jgaffiot <j.gaffiot@laposte.net>"]
license = "The Unlicense"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.21.26"
pendulum = "^2.1.2"
peewee = "^3.14.10"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
cpplint = "^1.6.0"
ipython = "^8.1.1"
flake8-bandit = "^3.0.0"
flake8-black = "^0.3.2"
flake8-bugbear = "^22.3.23"
pyupgrade = "^2.31.1"
ipdb = "^0.13.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ["py38"]
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.kdev4
)/
'''
